### ISSUE TITLE
Inconsistent Results with gammaALPs Package

### ISSUE THREAD

**Issue by RunminYao** [me-manu/gammaALPs#35]
Dear developers,

A colleague of mine attempted to duplicate the results (Left one of Figure 2) presented in the article [2112.14145] using the gammaALPs package, but found that the results did not match. Consequently, I tried my own package, but unfortunately, my results did not match with those presented in the article or the results of the gammaALPs package either. 
# Bug
Here are the results and the related implementation code.

|         gammaALPs         | My program  |
|:-------------------------:|:-----------:|
| ![GMF_before_debug](https://user-images.githubusercontent.com/22574567/227510901-6d1dae04-4770-4a46-816e-3115468828e7.png) | ![my](https://user-images.githubusercontent.com/22574567/227510946-f5bb8cf4-076e-4b50-ae42-62050fb68727.png) |

Implementation:
```python
from gammaALPs.core import Source, ALP, ModuleList
from gammaALPs.base import environs, transfer
import numpy as np
import matplotlib.pyplot as plt
from ebltable.tau_from_model import OptDepth
from astropy import constants as c
from matplotlib.patheffects import withStroke
from astropy import units as u

def draw(m_a,g):
    alp = ALP(m_a, g)

    EGeV = np.logspace(-2,4,1000)#

    pin = np.diag((0.5, 0.5, 0.))

    src = Source(z=0.031, ra='11h4m31s', dec='38d12m31.8s',bLorentz=13,theta_obs=np.radians(1))
    #src = Source(z=0.031, l=179.83167, b=65.03148,bLorentz=13,theta_obs=np.radians(1))

    ml = ModuleList(alp, src, pin=pin, EGeV=EGeV, seed=0)

    ml.add_propagation("Jet",0,B0=0.061,r0=2.5/30.86,rgam=2.5/30.86,
	    alpha=-1.,psi=0,helical=False,equipartition=False,Rjet= 1000.,n0=7.534e3,beta=-2.)
    ml.add_propagation("EBL", 1, eblmodel='franceschini')  # EBL attenuation comes second, after beam has left cluster
    ml.add_propagation("GMF", 2, model='jansson12')

    px, py, pa = ml.run()
    pgg = px + py  # the total photon survival probability

    for p in pgg: # plot all realizations
        plt.plot(ml.EGeV, p,label='m={:n},g={:n}'.format(m_a,g))
for m_a in [1,10,100]:
    draw(m_a,10)
draw(0.1,100)
plt.xscale("log")
plt.ylim(0,1)
plt.legend()
plt.show()
```
# Debug
After investigation, I discovered that the bug was caused by [the code below](https://github.com/me-manu/gammaALPs/blob/master/gammaALPs/core.py#L644), which updates the energies of all modules. This update overwrites the energy in the comoving reference in the jet of the blazar, resulting in inconsistency.
```python
# update energies of all modules
# also accounts for changed redshift
self.EGeV = self._EGeV
```

To solve the issue, I suggest modifying the setter function ["EGeV"](https://github.com/me-manu/gammaALPs/blob/master/gammaALPs/core.py#L404) of the "ModuleList" class in the same file as follows:
```python
@EGeV.setter
    def EGeV(self, EGeV):
        if type(EGeV) == u.Quantity:
            self._EGeV = EGeV.to('GeV').value
        else:
            self._EGeV = EGeV

        # update energies for all modules
        for m in self.modules:
            if type(m) == OptDepth:
                self._atten = np.exp(-self._eblnorm * m.opt_depth(self.source.z,EGeV / 1e3))
            elif type(m) == env.MixGMF:
                m.EGeV = EGeV
            elif type(m) == env.MixIGMFCell:
                m.EGeV = EGeV
                m._ee *= (1. + m._z_mean)
            elif type(m) == env.MixJet:
                m.EGeV = EGeV * (1. + self.source.z)
                m._ee /= m._source._doppler
            elif type(m) == env.MixJetHelicalTangled:
                m.EGeV = EGeV * (1. + self.source.z)
                m._ee /= m._gammas
            else:
                m.EGeV = EGeV * (1. + self.source.z)
        return
```

With this modification, the results obtained are consistent with mine if we do not consider the propagation in the galactic magnetic field. 

Results in the absence of the galactic magnetic field:
| gammaALPs before debug       | gammaALPs after debug       |
| ---------------------------- | --------------------------- |
| ![No_GMF_before_debug](https://user-images.githubusercontent.com/22574567/227513908-74d3ea0e-60d5-4b1e-9ce1-434761bb0e36.png) | ![No_GMF_after_debug](https://user-images.githubusercontent.com/22574567/227513938-01ff20d3-7d02-4678-a225-fb9cfe0f2c25.png) |

# Remaining issues
However, the results still disagree with mine in some cases if we consider the GMF part.

Results including the galactic magnetic field after debug:
![GMF_after_debug](https://user-images.githubusercontent.com/22574567/227515506-a2d32fce-079f-484b-828c-11e7a5d9825b.png)

My program obtains different magnetic field strengths from yours. Moreover, I noticed that the gammaALPs package uses a constant electron density profile instead of NE2001, which can be fixed by using the "pygedm" package (only workable on Linux platforms). Additionally, there exist some oscillations in the curves, which may be caused by the limit of the package's computational accuracy.

I am sorry I don't have time to fully check the GMF-related codes, here are what I noticed may be wrong. However, these bugs have little effect on the results. Please have a look at the GMF-related codes.
1. Maximum distance that beam traverses GMF to Earth. (Function “set_coordinates” of Class “MixGFM” in File “gammaALPs/gammaALPs/base/environs.py”)
[Line 1256](https://github.com/me-manu/gammaALPs/blob/master/gammaALPs/base/environs.py#L1256) is supposed to be: 
```Python
1./np.abs(cb) * ((-1)**(cb>0) * d * cl + np.sqrt(d**2 * cl**2 - d**2 + self.__rho_max**2))]) 
```

2. Vector Projection from GC cylindrical coordinates to HC galactic coordinates in cartesian basis. (Function “GC2HCproj” in File “gammaALPs/gammaALPs/utils/trafo.py”)
[Line 249](https://github.com/me-manu/gammaALPs/blob/master/gammaALPs/utils/trafo.py#L249) is supposed to be:
```python
result[1] = - sin(b) * (V[0]*cos(l-p) + V[1]*sin(l-p)) + cos(b) * V[2]
```
I hope this bug report helps in improving the gammaALPs package's functionality. If you require any further information from me, please let me know.

Best regards,
Runmin Yao

**Comment by RunminYao** [comment]
Dear @me-manu,
Here are some possible typos in Appendix F of your thesis, I hope this would be helpful.
1. Line 6 of second paragraph in Page 163: the equation should be $\rho=r_{-x}\exp[(\phi-180\degree)/\tan(90\degree-i)]$.
2. F.1 and F.2: equations should multiply by $[1-L(z,h_{disk},w_{disk})]$ instead of $L(z,h_{disk},w_{disk})$.
3. F.4: factor $-2$ missing in the exponent.
4. F.8: if $z<0$, $B_{\rho,X}=-b_{X}\cos(90\degree-\Theta_X)$.
5. F.10: $\rho=\sqrt{s^2\cos^2b+d^2+2sd\cos l\cos b}$.
6. F.14: $\hat{b}=-[\cos l \sin b\hat{x}+\sin l \sin b\hat{y}-\cos b\hat{z}]$.
7. F.18: $B_{t}=-\sin b[B_\rho \cos(l-\phi)+B_\phi\sin(l-b)]+B_z\cos b$.
8. F.19: $B_{u}=B_\rho\sin(\phi-l)+B_\phi\cos(\phi-l)$.
9. F.20: $\frac{1}{\cos b}(-d\cos l +\sqrt{d^2\cos^2l-d^2+\rho_{max}^2})$

Nevertheless, it's strange that some corresponding codes use correct formulas despite these typos in the thesis.

**Comment by me-manu** [comment]
Thanks @RunminYao. I need to check a few of your lines in more detail. A quick look gives me this:

1. Need to check  -> might also be wrong in the code
2. Agreed, but correct in the code 
3. Agreed, but correct in the code
4. Need to check -> might also be wrong in the code
5. Agreed, but correct in the code
6. Need to check
7. Follows from 6, different in code
8. Agreed, but correct in code.
9. Need to check, different in code

Let me get back to you with more update (I might open a separate issue for these GMF discussions).

**Comment by joshua-benabou** [comment]
Hello,

Similarly I have found that the GMF module is giving a conversion probability which seems to be off by 2 orders of magnitude in the above 10 keV range, and below 10 keV is off by many orders of magnitude. 

```
EGeV = 1e-5*np.logspace(-1., 1., 101)  # the energy range, roughly mathing the Fermi-LAT energy range
src = Source(z=0.017559, ra='17h45m50.5s', dec='-28d49m28s')  # some dummy source for initialization
pa_in = np.diag([0, 0, 1.])  # the inital polarization matrix; a pure ALP state

ml = ModuleList(ALP(m=0., g=1e-1), src, pin=pa_in, EGeV=EGeV, seed=0)

# add the GMF propagation module
ml.add_propagation("GMF", 0, model='jansson12')
px, py, pa = ml.run()
```
giving:

![image](https://github.com/me-manu/gammaALPs/assets/52699617/82ec0ee3-ba02-4cbb-990f-0702aa5493e9)

Is there any updated status on the issues raised above?

Separately, is there an easy way to find the conversion probabilities for the GMF only case, where the source is inside the milky way? Presumably specifying with redshift does not make sense in this case.

thanks!

**Comment by RunminYao** [comment]
> Thanks @joshua-benabou for your post. Unfortunately I'm completely swamped with teaching and other duties at the moment. I made some progress regarding the open issues above but I need to sit down for 1-2 days to regenerate plots to compare to the original J&F paper. E.g., point 6 above: I don't think the minus sign is correct as, in this case, you don't have a right-handed basis anymore. I hope I'll get to it in October... Sorry for the delay.

Hi @me-manu,
I don't think handness is important in this issue, since we only transform coordinate here. Although, the [galactic coordinate](https://en.wikipedia.org/wiki/Galactic_coordinate_system) (s, l, b) is a right-handed system (the order of axis matters). A more visual demonstration can be seen on [WOLFRAM Demonstrations Project](https://demonstrations.wolfram.com/). Alternatively, we can put it in this way: according to the definition of latitude b and the convention of z in J&F paper, b and z both positive towards the north, then the inner product of this two axis should be positive.

Additionally, below is my GMF module code. I hope it will be helpful in finding bugs.
```Python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
GMF module 

Functions
-----------
- s_max : calculate the maximum distance of the Milky Way.
- calculate_magnetic_field : calculate the galactic magnetic field of the Milky Way.

References
-----------
[1] Meyer M.
    The opacity of the universe for high and very high energy {gamma}-rays[J].
    2013.
    Caution: there are several typos for equations in this part of the reference.
[2] Jansson, Ronnie, and Glennys R. Farrar.
    A new model of the galactic magnetic field.
    The Astrophysical Journal 757.1 (2012): 14.
'''

import numpy as np
import sys

__all__ = ['s_max', 'calculate_magnetic_field']

'''
galactocentric cylindrical coordinates:(r, phi, z)
heliocentric spherical coordinates: (s, l, b)
'''

'''
Parameters of Model:
'''
d = -8.5e3

r_x = 1e3 * np.array([5.1,6.3,7.1,8.3,9.8,11.4,12.7,15.5])
b_j = 1e-6 * np.array([0.1,3.0,-0.9,-0.8,-2.0,-4.2,0.0,2.7])
b_ring = 0.1 *1e-6
h_disk = 400
w_disk = 270

B_n = 1.4e-6
B_s = -1.1e-6
r_n = 9.22e3
r_s = 1.67e4
w_h = 200
z_0 = 5.3e3

B_X = 4.6e-6
Theta_X0 = np.radians(49)
r_Xc = 4.8e3
r_X = 2.9e3

# jansson12b
#b_j[5] = -3.5e-6
#B_X = 1.8e-6


# jansson12c
'''
B_n = 1e-6
B_s = -0.8e-6
B_X = 3e-6
b_j[1], b_j[3], b_j[4] = 2e-6, 2e-6, -3e-6
'''
def logistic(z,h,w):
    return 1 / (1 + np.exp(-2*(np.abs(z) - h) / w))

def disk(coordinate_cylinder):
    '''
    Parameters:
    -----------
    galactocentric cylindrical coordinates:
        type: float64
        r: pc
        phi: rad
        z: pc
        
    Returns:
    -----------
    Magnetic field of disk/toroidal_halo/x_halo component in galactocentric cylindrical coordinates
        type: numpy.ndarray [B_r, B_phi, B_z]
        B_r, B_phi, B_z: G
    '''
    r, phi, z = coordinate_cylinder
    if (r < 3e3) or (r > 2e4):
        return np.array([0, 0, 0])
    elif (r < 5e3):
        return np.array([0, b_ring, 0])
    else:
        i = np.radians(11.5)
        boundary = np.concatenate((r_x * np.exp((phi - 3 * np.pi) / np.tan(np.pi / 2 - i)),\
                                   r_x * np.exp((phi - np.pi) / np.tan(np.pi / 2 - i)),\
                                  r_x * np.exp((phi + np.pi) / np.tan(np.pi / 2 - i))))
        bj = b_j[np.count_nonzero(boundary < r) % 8]
        B_r = bj * np.sin(i) * (5e3 / r) * (1-logistic(z,h_disk,w_disk))
        B_phi = bj * np.cos(i) * (5e3 / r) * (1-logistic(z,h_disk,w_disk))
        return np.array([B_r, B_phi, 0])

def toroidal_halo(coordinate_cylinder):
    '''
    Parameters:
    -----------
    galactocentric cylindrical coordinates:
        type: float64
        r: pc
        phi: rad
        z: pc
        
    Returns:
    -----------
    Magnetic field of disk/toroidal_halo/x_halo component in galactocentric cylindrical coordinates
        type: numpy.ndarray [B_r, B_phi, B_z]
        B_r, B_phi, B_z: G
    '''
    r, phi, z = coordinate_cylinder
    B_h = np.where(z < 0,B_s,B_n)
    r_h = np.where(z < 0,r_s,r_n)
    B_phi = np.exp(-np.abs(z)/z_0) * logistic(z,h_disk,w_disk) * B_h * (1 - logistic(r,r_h,w_h))
    return np.array([0,B_phi,0])

def x_halo(coordinate_cylinder):
    '''
    Parameters:
    -----------
    galactocentric cylindrical coordinates:
        type: float64
        r: pc
        phi: rad
        z: pc
        
    Returns:
    -----------
    Magnetic field of disk/toroidal_halo/x_halo component in galactocentric cylindrical coordinates
        type: numpy.ndarray [B_r, B_phi, B_z]
        B_r, B_phi, B_z: G
    '''
    r, phi, z = coordinate_cylinder
    if ((r**2+z**2)<1e6):
        return np.array([0, 0, 0])
    else:
        r_p = r - np.abs(z)/np.tan(Theta_X0)
        Theta_X = Theta_X0
        index = 1
        if (r_p < r_Xc):
            r_p = r * r_Xc / (r_Xc + np.abs(z)/np.tan(Theta_X0))
            if (r == r_p):
                Theta_X = np.arctan2(r_Xc * np.tan(Theta_X0), r_p)
            else:
                Theta_X = np.arctan2(np.abs(z), r - r_p)
            index = 2
        b_X = B_X * np.exp(-r_p / r_X)
        if (r <1e-15):
            B = b_X
        else:
            B = b_X * (r_p / r) ** index
        B_r = B * np.cos(Theta_X) * (-1) ** (z < 0)
        B_z = B * np.sin(Theta_X)
        return np.array([B_r, 0, B_z])

def coordinate_transform(coordinate_sphere):
    '''
    Parameters:
    -----------
    coordinate_sphere: heliocentric spherical coordinates
        type: tuple/numpy.ndarray (s, l, b)
        s: pc
        l: rad
        b: rad
        
    Returns:
    -----------
    galactocentric cylindrical coordinates
        type: tuple (r, phi, z)
        r: pc
        phi: rad
        z: pc
    '''
    s, l, b = coordinate_sphere
    r = ((s * np.cos(b)) ** 2 + 2 * d * s * np.cos(b) * np.cos(l) + d ** 2) ** 0.5
    phi = np.arctan2(s * np.sin(l) * np.cos(b), s * np.cos(l) * np.cos(b) +d)
    z = s * np.sin(b)
    return (r, phi, z)

def projection(B,coordinate_cylinder,coordinate_sphere):
    '''
    Parameters:
    -----------
    B: magnetic field in galactocentric cylindrical coordinates
        type: numpy.ndarray [B_r, B_phi, B_z]
        B_r, B_phi, B_z: G

    coordinate_cylinder: galactocentric cylindrical coordinates
        type: tuple (r, phi, z)
        r: pc
        phi: rad
        z: pc
    coordinate_sphere: heliocentric spherical coordinates
        type:tuple (s, l, b)
        s: pc
        l: rad
        b: rad
        
    Returns:
    -----------
    Magnetic field in heliocentric spherical coordinates
        type:tuple (B_s, B_u, B_t)
        B_s, B_u, B_t: G
    '''
    B_r, B_phi, B_z = B
    r, phi, z = coordinate_cylinder
    s, l, b = coordinate_sphere
    B_s = np.cos(b) * (B_r * np.cos(l - phi) + B_phi * np.sin(l - phi)) + B_z * np.sin(b)
    B_t = -np.sin(b) * (B_r * np.cos(l - phi) + B_phi * np.sin(l - phi)) + B_z * np.cos(b)
    B_u = B_r * np.sin(phi - l) + B_phi * np.cos(phi - l)
    return (B_s, B_u, B_t)

def calculate_magnetic_field(s,l,b,coordinate='sphere'):
    '''
    Parameters:
    -----------
    (s, l, b): heliocentric spherical coordinates
        type:float64
        s: pc
        l: rad
        b: rad
    coordinate: coordinate of output
        type:string
        coordinate: {'sphere','cylinder'}
        
    Returns:
    -----------
    Galactic Magnetic Field of the Milky Way
        type:tuple (B_s, B_u, B_t) / (B_r, B_phi, B_z)
        B_s, B_u, B_t: G
        B_r, B_phi, B_z: G
    '''
    coordinate_sphere = (s, l, b)
    coordinate_cylinder = coordinate_transform(coordinate_sphere)
    B_cylinder = disk(coordinate_cylinder) + toroidal_halo(coordinate_cylinder) + x_halo(coordinate_cylinder)
    if (coordinate=='sphere'):
        return projection(B_cylinder,coordinate_cylinder,coordinate_sphere)
    elif (coordinate=='cylinder'):
        return tuple(B_cylinder)
    else:
        raise

def s_max(l,b):
    '''
    Parameters:
    -----------
    (l, b): heliocentric spherical coordinates
        type:float64
        l: rad
        b: rad
        
    Returns:
    -----------
    Maximum distance of the Milky Way
        type:float64
        s: pc
    '''
    r_max = 2e4
    z_max = 5e4
    return np.min([((-1)**(np.cos(b)>0)*d * np.cos(l) + (d ** 2 * np.cos(l) ** 2 - d ** 2 + r_max ** 2) ** 0.5) / np.abs(np.cos(b)),\
                   z_max / np.abs(np.sin(b))])

def main():
    print(__doc__)
    try:
        argv = sys.argv
        s = float(argv[1])
        l = float(argv[2])
        b = float(argv[3])
        coordinate = 'sphere'
        string = "Magnetic field in heliocentric spherical coordinates(unit:G):\n"
        if (len(argv)==5):
            coordinate = argv[4]
            string = ("Magnetic field in galactocentric cylindrical coordinates(unit:G):\n"
                      if coordinate=='cylinder'
                      else "Magnetic field in heliocentric spherical coordinates(unit:G):\n") 
        print(string,calculate_magnetic_field(s,l,b,coordinate))
    except:
        print("usage: python calculate_magnetic_field.py <s/rad> <l/rad> <b/pc> [coordinate]\nexample: python GMF.py 1.0 1.1 200")

if __name__ == '__main__':
    main()
```

**Comment by RunminYao** [comment]
Hi @me-manu ,

I've checked the GMF-related codes and figured out what the problem is.
## Where the issue comes from
The main issue originates from the different choice of the reference frame of photons, or the reference frame of the Jet Field. Below is a demonstration of the [Galactic latitude and longitude](https://en.wikipedia.org/wiki/Galactic_coordinate_system#/media/File:Galactic_coordinates.JPG) and different settings of the reference frame. Here (s, l, b) and (x, y, z) denote the reference frame of the Milky Way and that of photons, respectively. 

|![Galactic_coordinates](https://github.com/me-manu/gammaALPs/assets/22574567/ac699932-d81a-442c-9a98-7cd3cbdd620a)|![diagram](https://github.com/me-manu/gammaALPs/assets/22574567/7eb7521b-be48-440e-81b1-f200b8968045)|
|---|---|
|Galactic coordinate|(a)My reference frame (b)The reference frame of the gammaALPs|

I choose the frame that parallelize the x-axis to the galactic plane in my program, while the gammaALPs uses the frame that align the x-axis with the b-axis. Then the angle of the magnetic field uses different expression:

$(a): \psi=np.arctan2(<\vec{B}, \hat{l}>, <\vec{B}, \hat{b}>)$
$(b): \psi=np.arctan2(<\vec{B}, -\hat{b}>, <\vec{B}, \hat{l}>)$

This also explains the minus sign of point 6 I mentioned above. 

The explanation above can be verified by an angle rotation of the Jet field. More specifically, change `psi` to `-np.pi/2` of the propagation in Jet in the original implementation code, then the gammaALPs gives a consistent figure as mine (with the bug fix of the `EGeV.setter` function).

```Python
    ml.add_propagation("Jet",0,B0=0.061,r0=2.5/30.86,rgam=2.5/30.86,
	    alpha=-1.,psi=-np.pi/2,helical=False,equipartition=False,Rjet= 1000.,n0=7.534e3,beta=-2.)
```
## The influence of the issue
In general, the choice of the reference frame (or the magnetic field angle of the jet) would not significantly change the survival probability of photons but the off-diagonal terms of the polarization density matrix. The difference was amplified in the implementation code, where much stronger couplings were chosen. For more general couplings, the differences are insignificant compared to measurement precision and other effects. The figure and its corresponding code below shows the difference caused by the magnetic field angle of the jet, considering some reasonable couplings. 
![Figure](https://github.com/me-manu/gammaALPs/assets/22574567/969df4c6-73dd-4cf6-aded-5e22225dca2e)
```Python
def draw(m_a,g,psi):
    #same code as the implementation code
    ml.add_propagation("Jet",0,B0=0.061,r0=2.5/30.86,rgam=2.5/30.86,
        alpha=-1.,psi=psi,helical=False,equipartition=False,Rjet= 1000.,n0=7.534e3,beta=-2.)
    #same code as the implementation code

for m_a in [1,10,100]:
    for g in [0.5,1,2]:
        for i in range(4):
            draw(m_a,g,i*np.pi/4)
            draw(m_a,g,-i*np.pi/4)
```

## The Xhalo component
During my examine, I found some other errors in [the codes of Xhalo component](https://github.com/me-manu/gammaALPs/blob/master/gammaALPs/bfields/gmf.py#L337), though they make no difference in the current case. Below is a bug fix for it.

```Python
    def BX(self, rho, z):
        """
        X (out of plane) component of galactic magnetic field 
        in galactocentric cylindrical coordinates (rho,phi,z)

        BX is purely poloidal, i.e. phi component = 0

        Parameters
        ----------
        rho: array-like
            N-dim array with distance from origin in GC cylindrical coordinates, is in kpc
        z: array-like
            N-dim array with height in kpc in GC cylindrical coordinates

        Returns
        -------
        BX, BX_abs: tuple of :py:class:`~numpy.ndarray`
            tuple containing the magnetic field of the X component as a (3,N)-dim array with (rho,phi,z)
            components of disk field for each coordinate tuple and absolute value of the field as
            N-dim array
        """

        if (not rho.shape[0] == z.shape[0]):
            warnings.warn("List do not have equal shape! returning -1", RuntimeWarning)
            return -1

        # BX vector in rho, phi, z
        # rows: rho, phi and z component
        BX = np.zeros((3, rho.shape[0]))
        m = np.sqrt(rho**2. + z**2.) >= 1.

        bx = lambda rho_p: self.BX0 * np.exp(-rho_p / self.rhoX)
        #tx = lambda rho, z, rho_p: np.arctan2(np.abs(z), (rho - rho_p))
        tx = lambda rho_p: np.arctan2(self.rhoXc*np.tan(self.ThetaX0), rho_p)#Another experssion that handle the z=0 (rho=rho_p) case

        rho_p = rho[m] * self.rhoXc/(self.rhoXc + np.abs(z[m] ) / np.tan(self.ThetaX0))

        m_rho_b = rho_p > self.rhoXc  # region with constant elevation angle
        m_rho_l = rho_p <= self.rhoXc  # region with varying elevation angle

        theta = np.zeros(z[m].shape[0])
        b = np.zeros(z[m].shape[0])

        rho_p0 = (rho[m])[m_rho_b]  - np.abs( (z[m])[m_rho_b] ) / np.tan(self.ThetaX0)
        b[m_rho_b] = bx(rho_p0) * rho_p0/ (rho[m])[m_rho_b]
        theta[m_rho_b] = self.ThetaX0 * np.ones(theta.shape[0])[m_rho_b]

        b[m_rho_l] = bx(rho_p[m_rho_l]) * (rho_p[m_rho_l]/(rho[m])[m_rho_l] )**2.
        theta[m_rho_l] = tx(rho_p[m_rho_l])
        #theta[m_rho_l] = tx((rho[m])[m_rho_l], (z[m])[m_rho_l], rho_p[m_rho_l])
        #mz = (z[m] == 0.)
        #theta[mz] = np.pi/2.

        #BX[0, m] = b * (np.cos(theta) * (z[m] >= 0) + np.cos(pi*np.ones(theta.shape[0]) - theta) * (z[m] < 0))
        #BX[2, m] = b * (np.sin(theta) * (z[m] >= 0) + np.sin(pi*np.ones(theta.shape[0]) - theta) * (z[m] < 0))
        #theta>0 from the definition
        BX[0, m] = b * np.cos(theta) * (-1) ** (z[m] < 0)#BX_rho points outward for z>0 and inward for z<0
        BX[2, m] = b * np.sin(theta)#BX_z points to north
                        
        return BX, np.sqrt(np.sum(BX**2.,axis=0))
```

**Comment by me-manu** [comment]
Thank you @RunminYao for all your work! I have implemented your changes. Could you checkout the  branch `fix-gmf-model` and test if everything works as expected now with the different definition of psi we are using in gammaALPs? I've also updated the `mixing_gmf` and `mixing_AGN_jet_simple` tutorial notebooks to explicitly show the coordinate system.

**Comment by RunminYao** [comment]
Thank you @me-manu for your maintenance! I have checked the branch `fix-gmf-model` and noticed two small problems.
1. You forgot to fix the `EGeV` setter function for  `MixIGMFCell` environment:
```Python
            elif type(m) == env.MixGMF:
                m.EGeV = EGeV
            elif type(m) == env.MixIGMFCell:
                m.EGeV = EGeV
                m._ee *= (1. + m._z_mean)
```
2. The definition of $\psi$ angle in the tutorial notebooks is supposed to be
$$\tan \psi = \frac{\langle\vec{B},-\hat{b}\rangle}{\langle\vec{B},\hat{l}\rangle},$$
since it's the angle between the B field and $\hat{y}$ axis. (Also see the definition of [numpy.arctan2](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html))

Other changes should be fine.

**Comment by me-manu** [comment]
Thanks a lot @RunminYao. Your suggested changes are implemented and everything is merged into master with PR #37
